In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\radhagopinath\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\radhagopinath\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\radhagopinath\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\radhagopinath\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\radhagopinath\anaconda3\lib\site-packages (from requests) (2025.4.26)

In [2]:
import requests

In [3]:
URL="https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)

In [5]:
json_data=res.json()

In [6]:
import pandas as pd

df=pd.json_normalize(json_data["data"])
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [11]:
#Homework
url="https://stephen-king-api.onrender.com/api/villains"
res=requests.get(url)
res

In [12]:
json_data=res.json()
json_data

{'data': [{'id': 1,
   'name': 'Bob Anderson',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Pownal residents',
    'Yarmouth residents',
    'Residents of Maine',
    'Villains',
    'Crime'],
   'created_at': '2023-11-13T23:49:22.390Z',
   'books': [],
   'shorts': [{'title': 'A Good Marriage',
     'url': 'https://stephen-king-api.onrender.com/api/book/180'}]},
  {'id': 2,
   'name': 'Kurt Barlow',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 2,
   'notes': ['Characters',
    "Jerusalem's Lot residents",
    'Residents of Maine',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:22.625Z',
   'books': [{'title': "Salem's Lot",
     'url': 'https://stephen-king-api.onrender.com/api/book/2'}],
   'shorts': []},
  {'id': 3,
   'name': 'Blaine the Mono',
   'gender': None,
   'status': 'Deceased',
   'types_id': 6,
   'notes': ['Characters',
    'Unsourced quotes',
    'The Dark Tower',
    'Villains',
    'Machines',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:22.743Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'},
    {'title': 'The Dark Tower III: The Waste Lands',
     'url': 'https://stephen-king-api.onrender.com/api/book/25'}],
   'shorts': []},
  {'id': 4,
   'name': 'Tina Blake',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Residents of Maine',
    'Chamberlain residents',
    'Bullies',
    'Name-continuity',
    'Lovers',
    'Bate High School students',
    'Villains',
    'Antagonists',
    'Carrie'],
   'created_at': '2023-11-13T23:49:22.968Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 5,
   'name': 'Malachai Boardman',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains', 'Antagonists'],
   'created_at': '2023-11-13T23:49:23.089Z',
   'books': [],
   'shorts': [{'title': 'Children of the Corn',
     'url': 'https://stephen-king-api.onrender.com/api/book/53'}]},
  {'id': 6,
   'name': 'James Boon',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains', "Jerusalem's Lot residents"],
   'created_at': '2023-11-13T23:49:23.203Z',
   'books': [],
   'shorts': [{'title': "Jerusalem's Lot",
     'url': 'https://stephen-king-api.onrender.com/api/book/58'}]},
  {'id': 7,
   'name': 'Henry Bowers',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Bullies',
    'Characters with mental illness',
    'Derry residents',
    'IT',
    'Residents of Maine',
    'Seekers of vengeance',
    'Villains',
    'Leaders',
    'Gang Leaders',
    'Slashers',
    'Victims',
    'LGBT',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:23.320Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 8,
   'name': 'Butch Bowers',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Derry residents',
    'Residents of Maine',
    'IT',
    'Antagonists',
    'Villains',
    'Bullies',
    'Characters with mental illness',
    'Spouses'],
   'created_at': '2023-11-13T23:49:23.438Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 9,
   'name': 'Greta Bowie',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Derry residents',
    'IT',
    'Residents of Maine',
    'Bullies',
    'Leaders',
    'Antagonists',
    'Status dependant on version',
    'Villains'],
   'created_at': '2023-11-13T23:49:23.561Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 10,
   'name': 'Marten Broadcloak',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Gilead residents',
    'The Dark Tower',
    'Residents of All-world',
    'Villains',
    'Lovers',
    'Multiverse'],
   'created_at': '2023-11-13T23:49:23.690Z',
   'books': [{'title': 'The Dark Tower: The Gunslinger',
     'url': 'https://stephen-king-api.onrender.com/api/book/12'}],
   'shorts': []},
  {'id': 11,
   'name': 'Christine (car)',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 6,
   'notes': ['Characters',
    'Objects',
    'Villains',
    'Christine',
    'Demonic items',
    'Antagonists',
    'Ghosts',
    'Murderers',
    'Seekers of vengeance'],
   'created_at': '2023-11-13T23:49:23.805Z',
   'books': [{'title': 'Christine',
     'url': 'https://stephen-king-api.onrender.com/api/book/13'}],
   'shorts': []},
  {'id': 12,
   'name': 'Isaac Chroner',
   'gender': None,
   'status': 'Deceased',
   'types_id': 6,
   'notes': ['Characters', 'Villains', 'Antagonists'],
   'created_at': '2023-11-13T23:49:23.918Z',
   'books': [],
   'shorts': [{'title': 'Children of the Corn',
     'url': 'https://stephen-king-api.onrender.com/api/book/53'}]},
  {'id': 13,
   'name': 'Winston Church',
   'gender': None,
   'status': 'Deceased',
   'types_id': 8,
   'notes': ['Characters',
    'Cats',
    'Villains',
    'Pet Sematary',
    'Status dependant on version',
    'Revived'],
   'created_at': '2023-11-13T23:49:24.039Z',
   'books': [{'title': 'Pet Sematary',
     'url': 'https://stephen-king-api.onrender.com/api/book/14'}],
   'shorts': []},
  {'id': 14,
   'name': 'Cindi',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Unknown fates',
    'Chamberlain residents',
    'Residents of Maine',
    'Bate High School students',
    'Bullies',
    'Villains',
    'Name-continuity',
    'Antagonists',
    'Victims',
    'Carrie'],
   'created_at': '2023-11-13T23:49:24.159Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 15,
   'name': 'Gage Creed',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'Villains',
    'Pet Sematary',
    'Status dependant on version',
    'Revived',
    'Antagonists',
    'Residents of Maine'],
   'created_at': '2023-11-13T23:49:24.285Z',
   'books': [{'title': 'Pet Sematary',
     'url': 'https://stephen-king-api.onrender.com/api/book/14'}],
   'shorts': []},
  {'id': 16,
   'name': 'Myra Crewes',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Chamberlain residents',
    'Residents of Maine',
    'Villains',
    'Bullies',
    'Ewen High School students',
    'Unknown fates',
    'Bate High School students',
    'Antagonists',
    'Victims',
    'Carrie'],
   'created_at': '2023-11-13T23:49:24.403Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 17,
   'name': 'Crimson King',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'The Dark Tower',
    'Multiverse',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:24.525Z',
   'books': [{'title': 'Insomnia',
     'url': 'https://stephen-king-api.onrender.com/api/book/29'},
    {'title': 'The Dark Tower: The Gunslinger',
     'url': 'https://stephen-king-api.onrender.com/api/book/12'},
    {'title': 'Black House',
     'url': 'https://stephen-king-api.onrender.com/api/book/38'},
    {'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'}],
   'shorts': []},
  {'id': 18,
   'name': 'Victor Criss',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Bullies',
    'Derry residents',
    'Residents of Maine',
    'IT',
    'Villains',
    'Antagonists',
    'Victims',
    'Status dependant on version'],
   'created_at': '2023-11-13T23:49:24.664Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 19,
   'name': 'Cujo',
   'gender': None,
   'status': 'Deceased',
   'types_id': 8,
   'notes': ['Characters',
    'Dogs',
    'Characters with mental illness',
    'Castle Rock residents',
    'Residents of Maine',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:24.799Z',
   'books': [{'title': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/book/10'}],
   'shorts': []},
  {'id': 20,
   'name': 'Arnie Cunningham',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Seekers of vengeance',
    'Lovers',
    'Christine',
    'Villains',
    'Antagonists',
    'Victims',
    'Heroes',
    'Protagonists'],
   'created_at': '2023-11-13T23:49:24.927Z',
   'books': [{'title': 'Christine',
     'url': 'https://stephen-king-api.onrender.com/api/book/13'}],
   'shorts': []},
  {'id': 21,
   'name': 'Dandelo',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 2,
   'notes': ['Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:25.057Z',
   'books': [{'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'}],
   'shorts': []},
  {'id': 22,
   'name': 'Norman Daniels',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Police',
    'Antagonists',
    'Villains',
    'Murderers'],
   'created_at': '2023-11-13T23:49:25.174Z',
   'books': [{'title': 'Rose Madder',
     'url': 'https://stephen-king-api.onrender.com/api/book/30'}],
   'shorts': []},
  {'id': 23,
   'name': 'Susan Day',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:25.311Z',
   'books': [{'title': 'Rose Madder',
     'url': 'https://stephen-king-api.onrender.com/api/book/30'},
    {'title': 'Insomnia',
     'url': 'https://stephen-king-api.onrender.com/api/book/29'}],
   'shorts': []},
  {'id': 24,
   'name': 'Cordelia Delgado',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Characters', 'Villains', 'The Dark Tower', 'Antagonists'],
   'created_at': '2023-11-13T23:49:25.430Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'}],
   'shorts': []},
  {'id': 25,
   'name': 'Billy deLois',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Chamberlain residents',
    'Residents of Maine',
    'Unknown fates',
    'Ewen High School students',
    'Bullies',
    'Villains',
    'Antagonists',
    'Carrie'],
   'created_at': '2023-11-13T23:49:25.546Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 26,
   'name': 'Horace M. Derwent',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 7,
   'notes': ['Stubs',
    'Characters',
    'Appearances',
    'The Shining',
    'Villains',
    'Ghosts',
    'LGBT'],
   'created_at': '2023-11-13T23:49:25.758Z',
   'books': [{'title': 'The Shining',
     'url': 'https://stephen-king-api.onrender.com/api/book/3'}],
   'shorts': []},
  {'id': 27,
   'name': 'Mordred Deschain',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'ESPers',
    'The Dark Tower',
    'Multiverse',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:25.873Z',
   'books': [{'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'}],
   'shorts': []},
  {'id': 28,
   'name': 'Bogs Diamond',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains', 'Leaders'],
   'created_at': '2023-11-13T23:49:25.992Z',
   'books': [],
   'shorts': [{'title': 'Rita Hayworth and Shawshank Redemption',
     'url': 'https://stephen-king-api.onrender.com/api/book/86'}]},
  {'id': 29,
   'name': 'Frank Dodd',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Police',
    'Murderers',
    'Villains',
    'Government employees',
    'Characters with mental illness',
    'The Dead Zone',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:26.115Z',
   'books': [{'title': 'The Dead Zone',
     'url': 'https://stephen-king-api.onrender.com/api/book/7'}],
   'shorts': []},
  {'id': 30,
   'name': 'Henrietta Dodd',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters', 'The Dead Zone', 'Villains'],
   'created_at': '2023-11-13T23:49:26.240Z',
   'books': [{'title': 'The Dead Zone',
     'url': 'https://stephen-king-api.onrender.com/api/book/7'}],
   'shorts': []},
  {'id': 31,
   'name': 'Rose the Hat',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Doctor Sleep',
    'Villains',
    'Harassers',
    'Murderers',
    'LGBT',
    'Bullies'],
   'created_at': '2023-11-13T23:49:26.355Z',
   'books': [{'title': 'Doctor Sleep',
     'url': 'https://stephen-king-api.onrender.com/api/book/52'}],
   'shorts': []},
  {'id': 32,
   'name': 'Rhea Dubativo',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Hambry residents',
    'The Dark Tower',
    'Residents of All-world',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:26.474Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'}],
   'shorts': []},
  {'id': 33,
   'name': 'Kurt Dussander',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:26.598Z',
   'books': [],
   'shorts': [{'title': 'Apt Pupil',
     'url': 'https://stephen-king-api.onrender.com/api/book/83'}]},
  {'id': 34,
   'name': 'Donald Merwin Elbert',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Villains',
    'Antagonists',
    'The Stand',
    'Characters with mental illness'],
   'created_at': '2023-11-13T23:49:26.707Z',
   'books': [{'title': 'The Stand',
     'url': 'https://stephen-king-api.onrender.com/api/book/5'}],
   'shorts': []},
  {'id': 35,
   'name': 'Marcia Fadden',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Characters',
    'Derry residents',
    'IT',
    'Residents of Maine',
    'Villains',
    'Bullies'],
   'created_at': '2023-11-13T23:49:26.820Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 36,
   'name': 'John Farson',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'The Dark Tower',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:26.944Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'}],
   'shorts': []},
  {'id': 37,
   'name': 'Randall Flagg',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'The Stand',
    'The Dark Tower',
    'Villains',
    'Bullies',
    'Leaders',
    'Revived',
    'Antagonists',
    'Meta-fiction',
    'Dystopian'],
   'created_at': '2023-11-13T23:49:27.063Z',
   'books': [{'title': 'The Stand',
     'url': 'https://stephen-king-api.onrender.com/api/book/5'},
    {'title': 'The Eyes of the Dragon',
     'url': 'https://stephen-king-api.onrender.com/api/book/17'},
    {'title': 'The Long Walk',
     'url': 'https://stephen-king-api.onrender.com/api/book/6'},
    {'title': 'The Dark Tower: The Gunslinger',
     'url': 'https://stephen-king-api.onrender.com/api/book/12'},
    {'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'},
    {'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'},
    {'title': 'The Dark Tower III: The Waste Lands',
     'url': 'https://stephen-king-api.onrender.com/api/book/25'}],
   'shorts': []},
  {'id': 38,
   'name': 'Kenny Garson',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Chamberlain residents',
    'Bullies',
    'Residents of Maine',
    'Villains',
    'Victims',
    'Bate High School students',
    'Unknown fates',
    'Antagonists',
    'Carrie'],
   'created_at': '2023-11-13T23:49:27.183Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 39,
   'name': 'John Garton',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Bullies',
    'Derry residents',
    'Residents of Maine',
    'IT',
    'Antagonists',
    'Villains',
    'Teachers'],
   'created_at': '2023-11-13T23:49:27.301Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 40,
   'name': 'Leland Gaunt',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 6,
   'notes': ['Characters', 'Villains', 'Castle Rock residents', 'Antagonists'],
   'created_at': '2023-11-13T23:49:27.414Z',
   'books': [{'title': 'Needful Things',
     'url': 'https://stephen-king-api.onrender.com/api/book/26'}],
   'shorts': []},
  {'id': 41,
   'name': 'Gerald Burlingame',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Antagonists',
    'Spouses',
    'Villains',
    "Gerald's Game",
    'Residents of Maine'],
   'created_at': '2023-11-13T23:49:27.535Z',
   'books': [{'title': "Gerald's Game",
     'url': 'https://stephen-king-api.onrender.com/api/book/27'}],
   'shorts': []},
  {'id': 42,
   'name': 'The Gladiators',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 5,
   'notes': ['Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:27.646Z',
   'books': [{'title': 'The Running Man',
     'url': 'https://stephen-king-api.onrender.com/api/book/11'}],
   'shorts': []},
  {'id': 43,
   'name': 'Peter Gordon',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Derry residents',
    'Residents of Maine',
    'Bullies',
    'Antagonists',
    'Victims',
    'IT',
    'Villains'],
   'created_at': '2023-11-13T23:49:27.764Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 44,
   'name': 'Mary Lila Grace',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Chamberlain residents',
    'Bullies',
    'Villains',
    'Lovers',
    'Carrie'],
   'created_at': '2023-11-13T23:49:27.890Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 45,
   'name': 'Delbert Grady',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 7,
   'notes': ['Characters',
    'Spouses',
    'Lovers',
    'Ghosts',
    'The Shining',
    'Villains',
    'Harassers'],
   'created_at': '2023-11-13T23:49:28.006Z',
   'books': [{'title': 'The Shining',
     'url': 'https://stephen-king-api.onrender.com/api/book/3'}],
   'shorts': []},
  {'id': 46,
   'name': 'Byron Hadley',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,

In [14]:
import pandas as pd

df=pd.json_normalize(json_data["data"])
df[["id","name"]]

      id               name
0      1       Bob Anderson
1      2        Kurt Barlow
2      3    Blaine the Mono
3      4         Tina Blake
4      5  Malachai Boardman
..   ...                ...
110  111      Percy Wetmore
111  112    William Wharton
112  113     Margaret White
113  114       Annie Wilkes
114  115     Tim Youngblood

[115 rows x 2 columns]

In [2]:
#Web Scraping

import requests as req

URL="https://www.scrapethissite.com/pages/simple/"
res=req.get(URL)
res

In [4]:
print(res.status_code)
if (res.status_code==200):
    print(res.text)

200
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [6]:
print(res.content)
print(res.headers)

b'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            \xc3\x85land\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-

In [7]:
with open("scraped_data/data1.html","w") as f:
    f.write(res.text)

In [8]:
#BeautifulSoup
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\radhagopinath\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\radhagopinath\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)

In [9]:
from bs4 import BeautifulSoup

with open("scraped_data/data1.html","r") as f:
    html_content=f.read()

soup=BeautifulSoup(html_content,"lxml")

In [10]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [11]:
soup.find("h3") #gives the first h3 tag occurence
soup.h3

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [26]:
all_h3=soup.find_all("h3")
all_countries=[]
for h3 in all_h3:
    name=h3.get_text(strip=True)
    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    all_countries.append([name,population])

In [31]:
import pandas as pd

df=pd.DataFrame(all_countries,columns=["Name","Population"])
df.to_csv("cleaned_data/data.csv",index=False)